version: 2

jobs:
  # Test Jobs
  build:
    docker:
      - image: golang:1.15.6
    steps:
      - checkout
      - run: make build

  test:
    docker:
      - image: golang:1.15.6
    steps:
      - checkout
      - run: make test/ci

  e2e-tests:
    docker:
      - image: docker:19.03.15
    steps:
      - checkout
      - run: |
          apk add make docker-compose
      - setup_remote_docker
      - run: |
          mkdir .well-known
          make e2e
          make e2e/env-stop

  e2e-tests/nocache:
    docker:
      - image: docker:19.03.15
    steps:
      - checkout
      - run: |
          apk add make docker-compose
      - setup_remote_docker
      - run: |
          mkdir .well-known
          REDIS_HOST=nocache make e2e
          make e2e/env-stop

  # Deploy Jobs
  deploy/sandbox:
    docker:
      - image: golang:1.15.6
    steps:
      - run: |
          curl -X POST \
               -F token=$GITLAB_CI_TOKEN \
               -F ref=master \
               -F "variables[DEPLOY_ENV]=sandbox" \
               -F "variables[CI_COMMIT_SHA]=$CIRCLE_SHA1" \
               https://gitlab.skypicker.com/api/v4/projects/1680/trigger/pipeline

  deploy/production:
    docker:
      - image: golang:1.15.6
    steps:
      - run: |
          curl -X POST \
               -F token=$GITLAB_CI_TOKEN \
               -F ref=master \
               -F "variables[DEPLOY_ENV]=production" \
               -F "variables[CI_COMMIT_SHA]=$CIRCLE_SHA1" \
               https://gitlab.skypicker.com/api/v4/projects/1680/trigger/pipeline

workflows:
  version: 2
  build:
    jobs:
      - build
  test:
    jobs:
      - test: &ignore-master
          filters:
            branches:
              ignore:
                - master
      - e2e-tests: *ignore-master
      - e2e-tests/nocache: *ignore-master
  deploy:
    jobs:
      - deploy/sandbox:
          filters:
            branches:
              only:
                - master
      - deploy/production:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
